-- E2E test schema for @supabase-labs/tanstack-db.
--
-- Column types mirror the Zod schemas in tests/test.utils.ts (ids are numeric,
-- so bigint identity keeps z.number() valid). This schema is intended for the
-- local Supabase stack the e2e suite boots — it is NOT a production schema.
create table public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  active boolean not null default true
);

create table public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  completed boolean not null default false
);

create table public.users_todos (
  user_id bigint not null references public.users (id) on delete cascade,
  todo_id bigint not null references public.todos (id) on delete cascade,
  primary key (user_id, todo_id)
);

-- Realtime: publish the tables so postgres_changes events fire for subscribers.
alter publication supabase_realtime
add
  table public.users;

alter publication supabase_realtime
add
  table public.todos;

alter publication supabase_realtime
add
  table public.users_todos;

-- Test-only posture: enable RLS with fully permissive policies. RLS must be ON
-- (not disabled) because Realtime's Postgres Changes uses SELECT policies to
-- decide what to broadcast — with RLS off, anon subscribers receive nothing.
-- The permissive policies let the anon key both CRUD via PostgREST and receive
-- every change. Do NOT copy this posture into a real application.
alter table
  public.users enable row level security;

alter table
  public.todos enable row level security;

alter table
  public.users_todos enable row level security;

create policy "e2e allow all" on public.users for all to public using (true) with check (true);

create policy "e2e allow all" on public.todos for all to public using (true) with check (true);

create policy "e2e allow all" on public.users_todos for all to public using (true) with check (true);

-- Reset helper called by the test setup (via the service_role key) between
-- tests. TRUNCATE has no PostgREST endpoint, so it is wrapped in a function.
-- security definer runs it as the owner; execute is restricted to service_role.
create
or replace function public.reset_e2e() returns void language sql security definer
set
  search_path = '' as $ $ truncate table public.users_todos,
  public.todos,
  public.users restart identity cascade;

$ $;

revoke execute on function public.reset_e2e()
from
  public,
  anon,
  authenticated;

grant execute on function public.reset_e2e() to service_role;